### ISSUE TITLE
detecting end of sql query resultset

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/MIMIC_HPO#35]
@aeyates for tasks that needs to go through a table, do some transformation and then insert into a new table, some of our code uses a row handler. It detects the end of the table by checking whether the current row_id matches max. When that happens, it inserts the last batch of results into the new table. I am just wondering what happens if the row_id is not arranged in order. I am not sure SELECT tries to sort the the result set; so it may leave some results not inserted if the max row_id happened in the middle?

**Comment by aeyates** [comment]
Good point, @kingmanzhang. I think something like this actually happened to me in the code I was writing and I ended up replacing the row_id with a count query and then keeping track of how many rows I'd processed. Let me dig through and I'll submit a pull request if I have a better way.

**Comment by kingmanzhang** [comment]
Makes sense. I figured out the same thing if it saves your time, https://github.com/TheJacksonLaboratory/MIMIC_HPO/blob/e9d96e5d4ba803935e98b46d16fff7e33dc6ae3a/src/main/java/org/jax/text2hpo/MimicRadiology2Hpo.java#L45
The other way I used before was manually control query batches:
https://github.com/TheJacksonLaboratory/MIMIC_HPO/blob/7dec9e5c03617a53a2023e78ba1f62638b7663e8/src/main/java/org/jax/service/InferLabHpoService.java#L77

**Comment by kingmanzhang** [comment]
done
