### ISSUE TITLE
Lazy initialization does not work

### ISSUE THREAD

**Issue by kingmanzhang** [TheJacksonLaboratory/MIMIC_HPO#38]
Added `@Lazy` to a text mining bean, but Spring still tries to initialize it (and raises exception). Need to fix. @ielis Any quick idea why adding `@Lazy` does not work?

https://github.com/TheJacksonLaboratory/MIMIC_HPO/blob/bbafdd6d77928794d4cde04f92d8b12cfd74edee/src/main/java/org/jax/text2hpo/UmlsText2HpoService.java#L21

**Comment by ielis** [comment]
Is this still current?

**Comment by kingmanzhang** [comment]
What is that?

**Comment by ielis** [comment]
If this is still an issue.

**Comment by kingmanzhang** [comment]
Let's keep it as is for now. Thanks.
